### ISSUE TITLE
Pointer to resume script if SSH connection times out

### ISSUE THREAD

**Issue by smaniktahla** [markusressel/zfs-inplace-rebalancing#11]
I've never gotten the job to complete because if my SSH connection times out in putty or my PC sleeps, when I resume, the script starts from the beginning of the file list, even though it doesn't reprocess the files it's already rebalanced. 

I'd like to request an enhancement, which is an option to write a flag for each file that's moved and then have the script resume from that point, rather than starting from the beginning. I realize that doing so would break rebalancing for multiple passes, which is why I suggest it be an option to enable.

**Comment by rattkin** [comment]
you can use standard linux tools made for this, for example `tmux`, `screen` etc.

**Comment by smaniktahla** [comment]
Understood. I wasn't aware of those tools until someone on Reddit mentioned tmux, so feel free to close this issue.
