### ISSUE TITLE
permission issue causing MD5 FAILED

### ISSUE THREAD

**Issue by rattkin** [markusressel/zfs-inplace-rebalancing#12]
It often stops (not always though) with this issue
```
Comparing copy against original...
MD5 FAILED:
---------------------- -rw-r--r--+ naser wheel 27ca390baf807f9728af92442217769b
!=
---------------------- -rwxr--r--+ naser wheel 27ca390baf807f9728af92442217769b
```

it seems to me that the MD5 matches, only the `x` permission is different.
I have issue with permissions sometimes (umask 022)

**Comment by markusressel** [comment]
Well the `MD5 FAILED:` message might be a bit misleading, its actually comparing everything you see printed afterwards. Not sure why its not copying the permissions though. Currently the script doesn't set permissions itself, but relies on `cp` to copy them correctly. Can you try to use the `cp` command and arguments from the script and run it manually to see what happens? Can you fix the permissions if you set them manually or by changing the arguments?

**Comment by rattkin** [comment]
If I set ZFS permissions again from the truenas gui, it is fixed.
The problem is probably only for files copied from desktop
