### ISSUE TITLE
Would rewriting blocks work too?

### ISSUE THREAD

**Issue by n3gwg** [markusressel/zfs-inplace-rebalancing#13]
Reading through some of the information here on this project I began to contemplate if there might be in any utility in doing something like using dd to read and rewrite each individual block in a file to accomplish the same mission intended by your code?

If so, this would mean that instead of needing enough space to hold the largest file in your directory, you would just need one free block worth of space. Moreover, one could set a number of blocks (if this idea would work), like read 10 blocks write 10 blocks, as it walked through the entire file.

Stuart

**Comment by markusressel** [comment]
Certainly sounds like an interesting idea. Not sure how practical this is using a bash script. If you try out something I would be more than happy to link to your repository :)

**Comment by markusressel** [comment]
Closing this for now, if you come up with something, let me know! 🤓
