### ISSUE TITLE
Help is no help

### ISSUE THREAD

**Issue by n3gwg** [markusressel/zfs-inplace-rebalancing#14]
root@test-box-not-quiz-box:~# ./zfs-inplace-rebalancing.sh 
Usage: zfs-inplace-rebalancing -checksum true -passes 1 /my/pool

See anything strange there?

It appears the the usage shows one dash as part of the parameter requirements not two. That is to say "-checksum" instead of "--checksum" (dash vs dash dash).

I would very respectfully request that this issue be remediated.

Stuart

**Comment by markusressel** [comment]
Sorry for the long wait, somehow I had notifications disabled.
Help message is fixed now.
