### ISSUE TITLE
Hardlinked files... How are they handled?

### ISSUE THREAD

**Issue by UltraHKR** [markusressel/zfs-inplace-rebalancing#19]
Hi, Mark

I have a simple question:
I have lots of hardlinked files in ZFS, they have been deduped with Czkawka.

How are they handled? Here's my use case:
/mnt/Zpool/downloads/media/some.ext
/mnt/Zpool/Media Library/Movies/Movie Name (xxxx)/correctname.ext (hardlink to some.ext)

Because I recently expanded my pool from 2x(12x 1.2TB SAS Raid-Z2) to 3x(12x 1.2TB SAS Raid-Z2) my storage is 60+% percent on the first 2x VDEV's (90+% full each) and the last VDEV is sitting empty...

**Comment by markusressel** [comment]
Thx to @johnpyp you can now skip hardlinks!
I hope this answers your question, so I will clise thus issue. Feel free to folloup if not! 🤓
