### ISSUE TITLE
line 60: bc: command not found

### ISSUE THREAD

**Issue by bitpushr** [markusressel/zfs-inplace-rebalancing#21]
Hey there,

Trying to run this on my TrueNAS Scale system. When doing so I just get "./zfs-inplace-rebalancing.sh: line 60: bc: command not found"

Seems to be related specifically to the "progress_percent=$(echo "scale=2; ${current_index}*100/${file_count}" | bc)" line in the code for the script.

Any ideas? Thanks!

**Comment by dcelasun** [comment]
`bc` is [GNU bc](https://www.gnu.org/software/bc/), a calculator of sorts. I'm not familiar with TrueNAS, but FreeBSD seems to have [a bc port](https://man.freebsd.org/cgi/man.cgi?query=bc&sektion=1) so you should be able to install that.

**Comment by markusressel** [comment]
There is an open PR to remove the dependency on `bc`, but the tests are failing: #20
