### ISSUE TITLE
Would you accept a freebsd PR?

### ISSUE THREAD

**Issue by duskmoss** [markusressel/zfs-inplace-rebalancing#43]
Hi just wondering if I made a little pull request that made the script run on freebsd (maybe also a bit in the read me about the dependencies for freebsd) would you accept it? 

Just a few minor changes . So far just changes to sed and stat format.  I'd test on freebsd and linux.

I know you don't use and rightly said you can't support FreeBSD,  so I understand if you'd rather not have anything more that makes it look like you do.

**Comment by markusressel** [comment]
Sure thing! We just have to make sure that we test the changes on all platforms (Linux, FreeBSD, Mac).

**Comment by rekh127** [comment]
I don't have a mac, if I get the PR ready would you be willing to test on Mac?

**Comment by markusressel** [comment]
Well I would, but I don't have a testing setup for all platforms either. Would be a great addition to the CI though.
In #41 OP used VMs to test other platforms, maybe we can do the same using GitHub Actions.

**Comment by duskmoss** [comment]
Okay, I'm not sure how to proceed on testin on mac then, but I'll open a PR that works on freebsd and linux at least. Since those are the main platforms, and what I'm doing shouldn't hit mac maybe thats enough, but we can go from there

**Comment by duskmoss** [comment]
I opened #44 I did end up changing things for mac... but looking at the manual pages I'm certain they were not working in the same way it wasn't for freebsd.

**Comment by duskmoss** [comment]
you're welcome!
