### ISSUE TITLE
Filenames with square brackets are not checked for skipping

### ISSUE THREAD

**Issue by JosiahWhite** [markusressel/zfs-inplace-rebalancing#6]
In the case that a filename is something like `/pool/projects/[2019] cool project/file.txt`, it will constantly be rebalanced, even if a prior run had balanced it.
This rebalancing will often be done silently, but depending on the filename, it will also print an error from grep relating to an invalid regular expression.

**Comment by zeus86** [comment]
I can confirm this, this happens also to me on a (as of now) recent (TrueNAS-12.0-U8) truenas-instance while rebalancing.

**Comment by zeus86** [comment]
To address this, it would be nice, if errors and warnings would have been logged into a seperate logfile to track such things down on longer runs...

**Comment by markusressel** [comment]
I agree :+1:

**Comment by markusressel** [comment]
@zeus86 I have added a section about logging to file to the README.

**Comment by zeus86** [comment]
awesome :+1:
