### ISSUE TITLE
Running in TrueNAS Scale: bc missing

### ISSUE THREAD

**Issue by crkinard** [markusressel/zfs-inplace-rebalancing#9]
./zfs-inplace-rebalancing.sh: line 60: bc: command not found

My guess it is something just missing in the base install of TrueNAS Scale. 
What are your thoughts running the script in a Docker container that has the missing component?

**Comment by evanrich** [comment]
if you download bc.deb you can extract and copy bc out. I just did this

http://ftp.us.debian.org/debian/pool/main/b/bc/bc_1.07.1-2+b2_amd64.deb

download that, use 7zip to extract, grab bc binary, chmod +x it and put it in /usr/bin...then works.

**Comment by rmcfadzean** [comment]
```sh
wget http://http.us.debian.org/debian/pool/main/b/bc/bc_1.07.1-2+b2_amd64.deb && \
dpkg -i bc_1.07.1-2+b2_amd64.deb && \
rm bc_1.07.1-2+b2_amd64.deb
```
is the quick and dirty line that I use

**Comment by evanrich** [comment]
that works too =)

**Comment by markusressel** [comment]
Sure, creating a docker image would be an option.

**Comment by markusressel** [comment]
There exists a Docker image now:
https://github.com/markusressel/zfs-inplace-rebalancing/pkgs/container/zfs-inplace-rebalancing

I will go ahead and close this issue. Feel free to open another if anything comes up.
